language: perl
sudo: false
perl:
  - "5.8"
  - "5.26"
install:
  - curl -sSL --compressed https://git.io/cpm | perl - install -g .
script:
  - perl Makefile.PL
  - make
  - make test
  - make install
